ProyectoCondominios/Models/Condominos.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Web;
namespace ProyectoCondominios.Models
{
    public class Condominos
    {
        public int? Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Telefonos { get; set; }
        public string Email { get; set; }
        public byte[] Foto { get; set; }
        public IFormFile Archivo { get; set; }
        public IEnumerable<SelectListItem> ListaCondominos { get; set; }
    }
}

ProyectoCondominios/Controllers/CondominosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Protocol.Plugins;
using ProyectoCondominios.Business;
using ProyectoCondominios.Models;
using Proyectocondominos.Business;
using Proyectocondominos.Models;
using System.Net.Mail;
using System.Net;
using ProyectoCondominios.Utilitarios;
using System.Drawing;
using System.Drawing.Imaging;

namespace ProyectoCondominios.Controllers
{
    public class CondominosController : Controller
    {
        private readonly IConfiguration _configuration;
        private UsuarioActivo _usuario;

        public CondominosController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            try
            {
                List<Condominos> result = CargarCondominos();

                return View(new ModeloBase { Datos = result, Error = new ErrorViewModel() });
            }
            catch (Exception ex)
            {
                return View(new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        public IActionResult Buscar(string palabraClave)
        {
            try
            {
                List<Condominos> result = CargarCondominos();

                if (string.IsNullOrEmpty(palabraClave))
                {
                    return View("Index", new ModeloBase { Datos = result, Error = new ErrorViewModel() });
                }
                palabraClave = palabraClave.ToLower();
                var buscador = result.Where(x => x.Nombre.ToLower().Contains(palabraClave) || x.Cedula.ToLower().Contains(palabraClave) ||
                    x.Telefonos.ToLower().Contains(palabraClave) || x.Email.ToLower().Contains(palabraClave)).ToList();
                return View("Index", new ModeloBase { Datos = buscador, Error = new ErrorViewModel(), Buscando = true  });
            }
            catch (Exception ex)
            {
                return View(new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        public IActionResult AgregarOEditar(int? id)
        {
            ValidarUsuario();
            var condomino = new Condominos();
            if (id != null)
            {
                var bus = new CondominosBusiness(_configuration);
                condomino = bus.Obtener(new Condominos { Id = id }, _usuario.Id).FirstOrDefault();
            }
            ViewBag.Usuario = _usuario;
            return View("AgregarOEditar", condomino);
        }

        public IActionResult Guardar(Condominos model)
        {
            try
            {
                ValidarUsuario();
                var bus = new CondominosBusiness(_configuration);

                //Convierte la imagen
                if (model.Archivo != null)
                {
                    var convertidor = new TransformadorDeImagenes();
                    model.Foto = convertidor.ConvertirImagenABlob(model.Archivo);
                }  
                
                if (model.Id == 0 || model.Id == null)
                {
                    string message = bus.CrearObteniendoMensaje(model, _usuario.Id);

                    if (!string.IsNullOrEmpty(message))
                    {
                        EnvioDeCorreoElectronico(message, model);
                    }                    
                }
                else
                {
                    bus.Editar(model, _usuario.Id);
                }
                List<Condominos> result = CargarCondominos();
                return View("Index", new ModeloBase { Datos = result, Error = new ErrorViewModel() });
            }
            catch (Exception ex)
            {
                return View("Index", new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        private static void EnvioDeCorreoElectronico(string message, Condominos modelo)
        {
            var senderEmail = new MailAddress(Constantes.EmailFrom, Constantes.EmailName);
            var receiverEmail = new MailAddress(modelo.Email, modelo.Nombre);
            var password = Constantes.EmailPass;
            string sub = "Registro de Condómino. Usuario";
            var body = message;
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(senderEmail.Address, password)
            };
            using (var mess = new MailMessage(senderEmail, receiverEmail)
            {
                Subject = sub,
                Body = body
            })
            {
                smtp.Send(mess);
            }
        }

        public IActionResult Eliminar(int id)
        {
            try
            {
                ValidarUsuario();
                var bus = new CondominosBusiness(_configuration);
                bus.Eliminar(id, _usuario.Id);

                List<Condominos> result = CargarCondominos();
                return View("Index", new ModeloBase { Datos = result, Error = new ErrorViewModel() });
            }
            catch (Exception ex)
            {
                return View("Index", new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        private List<Condominos> CargarCondominos()
        {
            ValidarUsuario();
            var bus = new CondominosBusiness(_configuration);
            var result = bus.Obtener(new Condominos(), _usuario.Id);
            ViewBag.Usuario = _usuario;
            return result;
        }

        private void ValidarUsuario()
        {
            var sessionValue = HttpContext.Session.GetString("Usuario");

            if (string.IsNullOrEmpty(sessionValue))
            {
                throw new Exception("Por favor inicie sesión");
            }

            _usuario = JsonConvert.DeserializeObject<UsuarioActivo>(sessionValue);
        }
    }
}

ProyectoCondominios/Views/Condominos/AgregarOEditar.cshtml
@using ProyectoCondominios.Models
@model Condominos
@{
    ViewData["Title"] = "Agregar o Editar";
}

@using (Html.BeginForm("Guardar", "Condominos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="text-center">
        <div class="row col-12">
            @if (Model.Id == null)
            {
                <h4>Agregar Condóminos</h4>
            }
            else
            {
                <h4>Editar Condóminos</h4>
            }
        </div>
    </div>
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Foto)
    <div class="row">
        <label style="float: left;">Cédula:</label>
        @Html.TextBoxFor(m => m.Cedula, null, new { @class = "form-control col-md-6", placeholder="Cédula", style="float: right;"})
    </div>
    <div class="row">
        <label style="float: left;">Nombre:</label>
        @Html.TextBoxFor(m => m.Nombre,  null, new { @class = "form-control", placeholder="Nombre", style="float: right;"})
    </div>
    <div class="row">
        <label style="float: left;">Teléfonos:</label>
        @Html.TextBoxFor(m => m.Telefonos,  null, new { @class = "form-control col-md-6", placeholder="Teléfonos", style="float: right;"})
    </div>
    <div class="row">
        <label style="float: left;">Email:</label>
        @Html.TextBoxFor(m => m.Email,  null, new { @class = "form-control col-md-6", placeholder="Email", style="float: right;"})
    </div>
    <div class="row">
        <label>Foto:</label>
    </div>
    <div>
        @{
            string etiquetaFoto = string.Empty;
            if (Model.Id == null)
            {
                etiquetaFoto = "Agregar foto";
            }
            else
            {
                etiquetaFoto = "Actualizar foto";
            }
            <input class="form-control"
               value="@etiquetaFoto"
               asp-for="Archivo" />

            if (Model.Foto != null)
            {
                var base64foto = Convert.ToBase64String(Model.Foto);
                var foto = String.Format("data:image/png;base64,{0}", base64foto);
                <br />
                <img src="@foto" style="width:200px; height:200px"/>
            }
        }
    </div>
    <br />
    <div class="row">
        @{
            string etiqueta = string.Empty;

            if (Model.Id == null)
            {
                etiqueta = "Crear";
            }
            else
            {
                etiqueta = "Guardar";
            }
        }
        <input type="submit" class="btn btn-success" value="@etiqueta" />
    </div>
}

ProyectoCondominios/Views/Condominos/Index.cshtml
@using ProyectoCondominios.Models
@model ModeloBase
@{
    ViewData["Title"] = "Condóminos";
    var condominos = (List<Condominos>)Model.Datos;
}

<div class="text-center">
    <h4>Condóminos</h4>
</div>
@if (!string.IsNullOrEmpty(Model.Error.Error))
{
    <br />
    <div class="alert alert-danger" role="alert">
        @Model.Error.Error
    </div>
}
else
{
    <div class="row-cols-12">
        <input type="button"
           value="+ Agregar"
           class="btn btn-success"
           onclick="location.href='@Url.Action("AgregarOEditar", "Condominos")'" />
    </div>
    <br />
    <div class="text-center">
        @if ((condominos != null && condominos.Count > 0) || Model.Buscando)
        {
            <div class="row">
                @using (Html.BeginForm("Buscar", "Condominos", FormMethod.Post))
                {
                    <div class="col-11" style="float:left;">
                        @Html.TextBox("palabraClave", null, new { @class = "form-control", placeholder="Buscar por Cédula, Nombre, Teléfono ó Email"})
                    </div>
                    <div style="float:right;">
                        <input type="submit" class="btn btn-success" value="Buscar" />
                    </div>
                }
            </div>
            <br />
        }

        @if (condominos != null && condominos.Count > 0)
        {
            
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Cédula</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Teléfonos</th>
                        <th scope="col">Email</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in condominos)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Cedula</td>
                            <td>@item.Nombre</td>
                            <td>@item.Telefonos</td>
                            <td>@item.Email</td>
                            <td>
                                <input type="button"
                           value="Editar"
                           class="btn btn-warning"
                           onclick="location.href='@Url.Action("AgregarOEditar", "Condominos", new { id = item.Id})'" />
                            </td>
                            <td>
                                <input type="button"
                           value="Eliminar"
                           class="btn btn-danger"
                           onclick="location.href='@Url.Action("Eliminar", "Condominos", new { id = item.Id})'" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <br />
            <div class="alert alert-warning" role="alert">
                No existen elementos para mostrar.
            </div>
        }
    </div>
}