ProyectoCondominios/Controllers/VehiculosPorProyectoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoCondominios.Business;
using ProyectoCondominios.Models;
using Proyectocondominos.Models;

namespace ProyectoCondominios.Controllers
{
    public class VehiculosPorProyectoController : Controller
    {
        private readonly IConfiguration _configuration;
        private UsuarioActivo _usuario;

        public VehiculosPorProyectoController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            try
            {
                var datos = ObtenerInformacion();
                return View(new ModeloBase { Datos = datos, Error = new ErrorViewModel() });
            }
            catch (Exception ex)
            {
                return View(new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        public IActionResult Buscar(string palabraClave)
        {
            try
            {
                var datos = ObtenerInformacion();
                if (string.IsNullOrEmpty(palabraClave))
                {
                    return View("Index", new ModeloBase { Datos = datos, Error = new ErrorViewModel() });
                }
                palabraClave = palabraClave.ToLower();
                var buscador = datos.Where(x => x.Placa.ToLower().Contains(palabraClave)).ToList();
                return View("Index", new ModeloBase { Datos = buscador, Error = new ErrorViewModel(), Buscando = true });
            }
            catch (Exception ex)
            {
                return View(new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        private List<Vehiculo> ObtenerInformacion()
        {
            ValidarUsuario();
            var bus = new VehiculosPorProyectoBusiness(_configuration);
            List<Vehiculo> vehiculos = bus.Obtener(new Vehiculo { Id = null, ProyectoId = _usuario.ProyectoId }, _usuario.Id);
            ViewBag.Usuario = _usuario;
            return vehiculos;
        }

        private void ValidarUsuario()
        {
            var sessionValue = HttpContext.Session.GetString("Usuario");

            if (string.IsNullOrEmpty(sessionValue))
            {
                throw new Exception("Por favor inicie sesión");
            }

            _usuario = JsonConvert.DeserializeObject<UsuarioActivo>(sessionValue);
        }
    }
}

ProyectoCondominios/Views/VehiculosPorProyecto/Index.cshtml
@using ProyectoCondominios.Models
@model ModeloBase
@{
    ViewData["Title"] = "Vehículos de libre accesso";
    var vehiculos = (List<Vehiculo>)Model.Datos;
}

<div class="text-center">
    <h4>Vehículos de libre accesso</h4>
</div>
@if (!string.IsNullOrEmpty(Model.Error.Error))
{
    <br />
    <div class="alert alert-danger" role="alert">
        @Model.Error.Error
    </div>
}
else
{      
    <div class="text-center">
        @if ((vehiculos != null && vehiculos.Count > 0) || Model.Buscando)
        {
            <div class="row">
                @using (Html.BeginForm("Buscar", "VehiculosPorProyecto", FormMethod.Post))
                {
                    <div class="col-11" style="float:left;">
                        @Html.TextBox("palabraClave", null, new { @class = "form-control", placeholder="Buscar por placa"})
                    </div>
                    <div style="float:right;">
                        <input type="submit" class="btn btn-success" value="Buscar" />
                    </div>
                }
            </div>
            <br />
        }

        @if (vehiculos != null && vehiculos.Count > 0)
        {

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Placa</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Color</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in vehiculos)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Placa</td>
                            <td>@item.Marca</td>
                            <td>@item.Modelo</td>
                            <td>@item.Color</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <br />
            <div class="alert alert-warning" role="alert">
                No existen elementos para mostrar.
            </div>
        }
    </div>
}