ProyectoCondominios/Models/Vehiculo.cs
namespace ProyectoCondominios.Models
{
    public class Vehiculo
    {
        public int? Id { get; set; }
        public string Placa { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }

        public int ProyectoId { get; set; }
    }
}

ProyectoCondominios/Controllers/VehiculoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ProyectoCondominios.Business;
using ProyectoCondominios.Models;
using Proyectocondominos.Models;

namespace ProyectoCondominios.Controllers
{
    public class VehiculoController : Controller
    {
        private readonly IConfiguration _configuration;
        private UsuarioActivo _usuario;

        public VehiculoController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            try
            {
                List<Vehiculo> result = CargarVehiculo();

                return View(new ModeloBase { Datos = result, Error = new ErrorViewModel() });
            }
            catch (Exception ex)
            {
                return View(new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        public IActionResult Buscar(string palabraClave)
        {
            try
            {
                List<Vehiculo> result = CargarVehiculo();

                if (string.IsNullOrEmpty(palabraClave))
                {
                    return RedirectToAction("Index", new ModeloBase { Datos = result, Error = new ErrorViewModel() });
                }
                palabraClave = palabraClave.ToLower();
                var buscador = result.Where(x => x.Marca.ToLower().Contains(palabraClave) || x.Placa.ToLower().Contains(palabraClave) ||
                    x.Color.ToLower().Contains(palabraClave) || x.Modelo.ToLower().Contains(palabraClave)).ToList();
                return RedirectToAction("Index", new ModeloBase { Datos = buscador, Error = new ErrorViewModel(), Buscando = true });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        public IActionResult AgregarOEditar(int? id)
        {
            ValidarUsuario();
            var vehiculo = new Vehiculo();
            if (id != null)
            {
                var bus = new VehiculoBusiness(_configuration);
                vehiculo = bus.Obtener(new Vehiculo { Id = id }, _usuario.Id).FirstOrDefault();
            }
            ViewBag.Usuario = _usuario;
            return View("AgregarOEditar", vehiculo);
        }

        public IActionResult Guardar(Vehiculo model)
        {
            try
            {
                ValidarUsuario();
                var bus = new VehiculoBusiness(_configuration);
                if (model.Id == 0 || model.Id == null)
                {
                    bus.Crear(model, _usuario.Id); 
                }
                else
                {
                    bus.Editar(model, _usuario.Id);
                }
                List<Vehiculo> result = CargarVehiculo();
                return RedirectToAction("Index", new ModeloBase { Datos = result, Error = new ErrorViewModel() });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", new ModeloBase { Error = new ErrorViewModel { Error = ex.Message } });
            }
        }

        private List<Vehiculo> CargarVehiculo()
        {
            ValidarUsuario();
            var bus = new VehiculoBusiness(_configuration);
            var result = bus.Obtener(new Vehiculo(), _usuario.Id);
            ViewBag.Usuario = _usuario;
            return result;
        }

        private void ValidarUsuario()
        {
            var sessionValue = HttpContext.Session.GetString("Usuario");

            if (string.IsNullOrEmpty(sessionValue))
            {
                throw new Exception("Por favor inicie sesión");
            }

            _usuario = JsonConvert.DeserializeObject<UsuarioActivo>(sessionValue);
        }
    }
}

ProyectoCondominios/Views/Vehiculo/AgregarOEditar.cshtml
@using ProyectoCondominios.Models
@model Vehiculo
@{
    ViewData["Title"] = "Agregar o Editar";
}

@using (Html.BeginForm("Guardar", "Vehiculo", FormMethod.Post))
{
    <div class="text-center">
        <div class="row col-12">
            @if (Model.Id == null || Model.Id == 0)
            {
                <h4>Agregar Visita</h4>
            }
            else
            {
                <h4>Editar Visita</h4>
            }
        </div>
    </div>
    @Html.HiddenFor(m => m.Id)    
    <div class="row">
        <label style="float: left;">Placa:</label>
        @Html.TextBoxFor(m => m.Placa, null, new { @class = "form-control col-md-6", placeholder="Placa", style="float: right;"})
    </div>
    <div class="row">
        <label style="float: left;">Marca:</label>
        @Html.TextBoxFor(m => m.Marca,  null, new { @class = "form-control", placeholder="Marca", style="float: right;"})
    </div>
    <div class="row">
        <label style="float: left;">Modelo:</label>
        @Html.TextBoxFor(m => m.Modelo,  null, new { @class = "form-control col-md-6", placeholder="Modelo", style="float: right;"})
    </div>
    <div class="row">
        <label style="float: left;">Color:</label>
        @Html.TextBoxFor(m => m.Color,  null, new { @class = "form-control col-md-6", placeholder="Color", style="float: right;"})
    </div>
    <br />
    <div class="row">
        @{
            string etiqueta = string.Empty;

            if (Model.Id == null || Model.Id == 0)
            {
                etiqueta = "Crear";
            }
            else
            {
                etiqueta = "Guardar";
            }
        }
        <input type="submit" class="btn btn-success" value="@etiqueta" />
    </div>
}

ProyectoCondominios/Views/Vehiculo/Index.cshtml
@using ProyectoCondominios.Models
@model ModeloBase
@{
    ViewData["Title"] = "Vehículos";
    var lista = (List<Vehiculo>)Model.Datos;
}

<div class="text-center">
    <h4>Vehículos</h4>
</div>
@if (!string.IsNullOrEmpty(Model.Error.Error))
{
    <br />
    <div class="alert alert-danger" role="alert">
        @Model.Error.Error
    </div>
}
else
{
    <div class="row-cols-12">
        <input type="button"
           value="+ Agregar"
           class="btn btn-success"
           onclick="location.href='@Url.Action("AgregarOEditar", "Vehiculo")'" />
    </div>
    <br />
    <div class="text-center">
        @if ((lista != null && lista.Count > 0) || Model.Buscando)
        {
            <div class="row">
                @using (Html.BeginForm("Buscar", "Vehiculo", FormMethod.Post))
                {
                    <div class="col-11" style="float:left;">
                        @Html.TextBox("palabraClave", null, new { @class = "form-control", placeholder="Buscar por Placa, Marca, Modelo ó Color"})
                    </div>
                    <div style="float:right;">
                        <input type="submit" class="btn btn-success" value="Buscar" />
                    </div>
                }
            </div>
            <br />
        }
        @if (lista != null && lista.Count > 0)
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Placa</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Modelo</th>
                        <th scope="col">Color</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in lista)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Placa</td>
                            <td>@item.Marca</td>
                            <td>@item.Modelo</td>
                            <td>@item.Color</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <br />
            <div class="alert alert-warning" role="alert">
                No existen elementos para mostrar.
            </div>
        }
    </div>
}